#!/usr/bin/env bash

readdir_sink(){
  bin=$1
  local dir=$(which $1)
      #   lastpath=${dir##*/}
        basedir=$(basename $dir)
        dir=${dir%/*}

  if [ -d $dir/node_modules/$basedir ];then
     dir=$dir/node_modules/$basedir
  fi
  if [[ $(uname -s) = Darwin ]];then
     dir=${dir%/*}/lib/node_modules/$basedir
  fi
  #echo $dir

  ## get soft link 
  local cli=$(ls -l $dir)
        clis=($cli)
  local cli_i=${#clis[@]}
        cli_i=$((cli_i-1))

  echo ${clis[$cli_i]} 
}
# cli=$(readdir cg-cli)

readdir(){
  bin=$1
  local dir=$(which $1)
        basedir=$(basename $dir)
        dir=${dir%/*}

  ## fix softlink
  if [ -d $dir/node_modules/$basedir ];then
     dir=$dir/node_modules/$basedir
  fi

  #once again
  if [ -d $(dirname $dir)/lib/node_modules/$basedir ];then
     dir=$(dirname $dir)/lib/node_modules/$basedir
  fi
  ## end fix softlink

  # fix Darwin
  if [ ! -d $dir ];then
    if [[ $(uname -s) = Darwin ]];then
       dir=${dir%/*}/lib/node_modules/$basedir
    fi
  fi
  ## end fix Darwin

  echo $dir
}

usage(){
   cat <<- EOF
	EOF
 	cat <<- EOF
    usage: cg-cli [OPTIONS] [args..]
           cg-cli local update [table-name]

    OPTIONS:
      -h --help                  --print usage
         --show-endpoint         --show current endpoint
         --show-local            --show lcoal sql file path
         --show-default <field>  --show default fields
	EOF
	exit
}
if [ ${#@} = 0 ];then 
  usage
fi


## main 
clidir=$(readdir cg-cli)
clijs=$clidir/cg-cli.js

## check options
local_cmd=$9
update_cmd=$9
table_name_opt=$9
show_ep_opt=
show_sql_opt=
show_default_opt=
show_default_field_opt=
for opt in $@;do
   if [[ $opt = '-h' ]];then 
      usage
   elif [[ $opt = '--help' ]];then 
      ## do nothing, show java usage
      opt=$opt
   elif [[ $opt = 'local' ]];then
      local_cmd=$opt
   elif [[ $opt = 'update' ]];then
      update_cmd=$opt
   elif [[ $local_cmd && $update_cmd ]];then
      table_name_opt=$opt
## show endpoint
   elif [[ $opt = --show-endpoint ]];then 
      show_ep_opt=$opt
## show local sql file
   elif [[ $opt = --show-local ]];then 
      show_sql_opt=$opt
## show default
   elif [[ $opt = --show-default ]];then 
      show_default_opt=$opt
   elif [ $show_default_opt ];then
      show_default_field_opt=$opt
      unset show_default_opt
   fi
done

if [ $show_ep_opt ];then 
#   echo $cli/cg-cli.js show-endpoint
  node $clijs show-endpoint
elif [ $show_sql_opt ];then
  echo $clijs show-local
  node $clijs show-local
elif [ $show_default_opt ];then 
#   echo $cli/cg-cli.js show-default
  node $clijs show-default
elif [ $show_default_field_opt ];then 
#   echo $cli/cg-cli.js show-default-field $show_default_field_opt
  node $clijs show-default-field $show_default_field_opt

elif [ $update_cmd ];then 
   if [ $table_name_opt ];then
      # echo $cli/cg-cli.js update-table-entity $table_name_opt
      node $clijs update-table-entity $table_name_opt
   else
      # echo $cli/cg-cli.js update-table-entity
      node $clijs update-table-entity
   fi

else
   ## directly show nodejs commands
   # echo $(readdir)/cg-cli.js $@
   node $clijs $@
fi
